services:
  redis:
    image: redis:alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
      restart: always
    networks:
      - app_net

  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy
     restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - app_net

networks:
  app_net:
    name: hng_network # Fixes 'compose_named_network'
